### PR TITLE
Message stack training

### PR DESCRIPTION
**Pull request by liatsade**
https://www.gitbook.com/book/amitaibu/the-gizra-way/edit#/edit/message-stack/message_stack.md

### CODE REVIEW

**Comment by liatsade** [comment]
@RachelBaram ready for review.

**Comment by amitaibu** [comment]
Needs a re-roll

**Comment by RachelBaram** [comment]
@liatsade Is this done?

**Comment by liatsade** [comment]
@RachelBaram I fixed the conflict. Ready for last review and merge.

**Comment by RachelBaram** [comment]
@liatsade It is indicating that there is still a conflict.

**Comment by liatsade** [comment]
@RachelBaram It's because you merged other branch after I fixed this, so the conflict with the summary file (the GitBook menu) created again.
Fixed :-)

**Pull request merged**
