### PR TITLE
Work flow with Client

### PR DESCRIPTION
**Pull request by RachelBaram**
Describe our workflow with the clients, documentation requirements per each step, and Gizra contact points.

https://www.gitbook.com/book/amitaibu/the-gizra-way/edit#/edit/work-flow/work_flow_with_clients.md

### CODE REVIEW

**Comment by RachelBaram** [comment]
@amitaibu The only thing that is required before publishing is clarification about the difference between Account Manager (Efrat), Project Manager (Noam), and Team Lead in Gizra. Help. ;)

**Comment by amitaibu** [comment]
Needs a re-roll - you can see by seeing the "Merge" button is disabled.

screen shot 2016-11-02 at 9 35 08 am

## 

Noam = Efrat =  Account Manager =  Project Manager = Gizra is doing a mess with job titles 😉 

Team Lead = Senior developer = Helps the PM translate the devs problems/ client needs to technical building blocks.

**Comment by RachelBaram** [comment]
@amitaibu Are you OK that we close on Account Manager? Choose one please.
How do I re-roll? I only know what that means in D&D.

**Comment by amitaibu** [comment]
From the command line:

```
git checkout master # Chekout to master
git pull # Get most updated master
git checkout - # Back to this branch
git merge master # Merge changes from master
```

At this point you will see a conflict (also GitHub shows it)
screen shot 2016-11-02 at 9 57 31 am

Fix the conflict and

```
git commit -am "Resolve conflicts"
```

**Comment by amitaibu** [comment]
> Are you OK that we close on Account Manager?

Yes.

**Comment by RachelBaram** [comment]
@amitaibu Ready to publish. Liat helped me with the conflict. ;)

**Comment by RachelBaram** [comment]
Thanks! And, yes, I should have taken the WIP off the title. My apologies.

**Pull request merged**
