### PR TITLE
Escalation and timeboxing

### PR DESCRIPTION
**Pull request by liatsade**
https://www.gitbook.com/book/amitaibu/the-gizra-way/edit#/edit/escalation-and-timeboxing/escalation_and_timeboxing.md

### CODE REVIEW

**Comment by liatsade** [comment]
@RachelBaram ready for review.

**Comment by RachelBaram** [comment]
@liatsade Done editing. 
@amitaibu This is the training that Liat will be doing with the developers this Monday. It was put together with Brice's input. It is important that you read this before then so we go into that meeting fully aligned.

**Comment by liatsade** [comment]
@amitaibu ready for review. 
I want to be able to merge it till Monday, so it can be used as document of the training. I hope it fits your schedule.

**Comment by amitaibu** [comment]
@RachelBaram if ok by you, please merge

**Pull request merged**
