### PR TITLE
Work life balance

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
cc @RachelBaram

**Comment by amitaibu** [comment]
Putting everything out ;)

**Comment by RachelBaram** [comment]
Great idea!

**Comment by amitaibu** [comment]
@RachelBaram can you please review current work, and add/ change whatever you see fit

**Comment by RachelBaram** [comment]
@amitaibu  Github question... where exactly do I review the whole work-life section so I can edit it.

**Comment by amitaibu** [comment]
You can edit via gitbook - https://www.gitbook.com/book/amitaibu/the-gizra-way/edit#/edit/work-life/fly_or_fight_dealing_with_pressure.md

fly_or_fight_dealing_with_pressure_md__work-life__-_gitbook_editor

**Comment by RachelBaram** [comment]
The Gitbook was the first place I looked and it did not show up.  The link you provided brought me to the right place. How do I get there next time without you having to provide the link? Thanks!

screenclip

**Comment by RachelBaram** [comment]
@amitaibu I reviewed this section and made some small edits. Some points:

> You don't get along with your direct boss.... it's worth raising the point early on.

To whom and how? This can be seen as "going over someone's head" and it can undermine team leads, etc. Do all employees get regular 1 on 1 time with the owners? How does this work today?

> If the case is not getting along with the owners... you are also encouraged to approach HR or another liaison and have them help you with this matter.

Who is this? Here I believe it is important to be specific.

> You don't feel appreciated...Furthermore, determine if your work is being bubbled up properly. 

I don't understand what you intended to say here.

> If it is not ,e.g. as an account manager no one seems to appreciate all your projects are on time, find a way to make it clear. It doesn't have to be a meeting, which we normally discourage, but rather some mechanism to show success/ failure.

We talk about employees feeling free to speak up but then write that meetings are discouraged. Your point is only getting partially across.

**Comment by amitaibu** [comment]
Thanks, I'll clarify the comments.

> How do I get there next time without you having to provide the link? 

Branch name on GitHub:

work_life_balance_by_amitaibu_ _pull_request__3_ _gizra_gizra-way-book

Branch name on GitBook:

fly_or_fight_dealing_with_pressure_md__work-life__-_gitbook_editor

**Comment by amitaibu** [comment]
currently the GitBook and GitHub PRs workflow is a bit messy, I'll have to figure out a better way - until then you can edit where you want ;)

**Comment by amitaibu** [comment]
@Re Who is this? Here I believe it is important to be specific.

I prefer not to have people's name in the book - it's about a role, not a specific person.

**Comment by amitaibu** [comment]
@RachelBaram can you give it a final overview (it's on the `master` branch)

**Comment by RachelBaram** [comment]
@amitaibu Looks good. In general, I plan to only do light edits in order to keep your voice. I can make everything sound more official but IMO that contradicts what we are doing here.

**Comment by amitaibu** [comment]
Cool, I'm going to tweet about it soon :)

**Pull request merged**
