### PR TITLE
Add link and instruction to trivia game

### PR DESCRIPTION
**Pull request by liatsade**
https://www.gitbook.com/book/amitaibu/the-gizra-way/edit#/edit/who-are-we-trivia/who_are_we_-_trivia_game.md

### CODE REVIEW

**Comment by amitaibu** [comment]
Not a big fan. The trivia here is basically "reading comprehension" - checking you read the text and understood it. It was nice as a company thing, but I don't think it should be in the book.

**Comment by liatsade** [comment]
I think we should keep it for new employees. It's a nice way to learn about Gizra when you on boarding. Maybe the book is not the right place... but I can't think where else to put this, so we can remember it's there.

**Comment by amitaibu** [comment]
>  It's a nice way to learn about Gizra when you on boarding

But you learn from the chapter, not from the Trivia.

**Comment by liatsade** [comment]
I moved it to Training section.

**Comment by amitaibu** [comment]
👍

**Comment by RachelBaram** [comment]
@liatsade Can you please resolve the conflicting files.

**Comment by liatsade** [comment]
@RachelBaram done. No conflict now.

**Pull request merged**
