### PR TITLE
Productivity user guide

### PR DESCRIPTION
**Pull request by liatsade**
https://www.gitbook.com/book/gizra/the-gizra-way/edit#/edit/productivity-user-guide/productivity/productivity-user-guide.md?_k=5aujq9

### CODE REVIEW

**Comment by liatsade** [comment]
@RachelBaram please review and merge. Thanks.

**Comment by amitaibu** [comment]
The images have projects name, which they shouldn't

**Comment by liatsade** [comment]
You're right of course, thanks, I will fix it.

**Comment by liatsade** [comment]
The images were replaced with blurred images.

**Review by RachelBaram — COMMENTED** [review]
I made some edits. I am missing what the letters mean: E - empty, V - vacation, W - weekend, H- holiday, etc.

**Comment by liatsade** [comment]
Thanks, I added the letters meaning.

**Pull request merged**
